name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/bq-redesign
          echo ${{ secrets.PWD }} | sudo -S npm i --prefix frontend
          cd backend/BqApi
          echo ${{ secrets.PWD }} | sudo -S dotnet build
          echo ${{ secrets.PWD }} | sudo -S dotnet publish -c Release
          echo ${{ secrets.PWD }} | sudo -S dotnet dotnet-ef database update
          echo ${{ secrets.PWD }} | sudo -S pm2 restart all